[tool.poetry]
name = "habittracker"
version = "0.1.0"
description = ""
authors = ["kirill <kirill48108@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.8"
djangorestframework = "^3.15.2"
drf-spectacular = "^0.27.2"
django-cors-headers = "^4.6.0"
celery = "^5.4.0"
redis = "^5.0.8"
requests = "^2.32.3"
python-dotenv = "==1.2.1"
psycopg2-binary = "==2.9.11"
pillow = "==12.0.0"
django-filter = "==25.2"
djangorestframework-simplejwt = "==5.3.1"
pytest = "^9.0.1"
gunicorn = "^23.0.0"
celery-types = "^0.23.0"
djangorestframework-stubs = "^3.16.6"
pytest-django = "^4.11.1"

[tool.poetry.group.dev.dependencies]
coverage = "^7.11.3"
black = "==25.9.0"
isort = "==7.0.0"
flake8 = "^7.3.0"


[tool.poetry.group.lint.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 100
force_alphabetical_sort_within_sections = true
skip = ["venv", "migrations"]


[tool.pytest.ini_options]

DJANGO_SETTINGS_MODULE = "config.settings"

python_files = ["tests.py", "test_*.py", "*_tests.py"]

addopts = "--reuse-db"